#!/bin/sh

JAVA_OPTIONS="$JAVA_OPTIONS -DPERL_SERVER=scripts"
JAVA_OPTIONS="$JAVA_OPTIONS -Xmx512m"
# JAVA_OPTIONS="$JAVA_OPTIONS -DdebugPerlServer=3" 

if [ "$1" == "-debug" ]
then
    JAVA_OPTIONS="$JAVA_OPTIONS -Xdebug -Xrunjdwp:transport=dt_socket,address=8787,server=y,suspend=y"
fi

java $JAVA_OPTIONS -jar lib/adapterTool.jar $1 $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18}
