package DataNokiaCheckpoint;

use strict;
use warnings;
use Exporter 'import';
our @EXPORT_OK = qw($responsesNokiaCheckpoint);

our $responsesNokiaCheckpoint = {};

$responsesNokiaCheckpoint->{'motherboard'} = <<'END';
IP440Lab[admin]# ipsctl hw:motherboard:serialnumber
hw:motherboard:serialnumber = IUS200418365
IP440Lab[admin]# ipsctl hw:motherboard:revision
hw:motherboard:revision = AA754558-205
IP440Lab[admin]# ipsctl hw:motherboard:modelname
hw:motherboard:modelname = SE440BX-2
IP440Lab[admin]#
END

$responsesNokiaCheckpoint->{'hw:chassis:serialnumber'} = <<'END';
ipsctl hw:chassis:serialnumber
hw:chassis:serialnumber = 8A000905808
IP440Lab[admin]#

END

$responsesNokiaCheckpoint->{'product:model'} = <<'END';
dbget product:model
IP400
IP440Lab[admin]#

END

$responsesNokiaCheckpoint->{hdd} = <<'END';
clish -c "show disk 0"
model    WDC WD84AA
type     IPSO DISK
capacity 8455MB
geometry 1027 x 255 X 63
location 0
IP440Lab[admin]#

END

$responsesNokiaCheckpoint->{snmp} = <<'END';
cat /var/etc/snmpd.conf
#  This file was AUTOMATICALLY GENERATED
#  Generated by snmp_xlate on Mon Apr 16 15:38:21 2007
# 
#  DO NOT EDIT
# 

sysLocation Austin-alterpoint
sysContact pitest
coldstartenable  1
linktrapenable  1
frdlcistatuschangeenable  1
authtrapenable  2
vrrptrapnewmasterenable  2
vrrptrapauthfailureenable  2
systemtrapconfigurationchangeenable  1
systemtrapconfigurationfilechangeenable  1
systemtrapconfigurationsavechangeenable  1
systemtraplowdiskspaceenable  2
systemtrapnodiskspaceenable  2
systemtrapdiskfailureenable  2
systemtrapdiskmirrorsetcreateenable  2
systemtrapdiskmirrorsetdeleteenable  2
systemtrapdiskmirrorsyncsuccessenable  2
systemtrapdiskmirrorsyncfailureenable  2
clusternewmasterenable  2
clustermemberleftenable  2
clustermemberjoinenable  2
clustermemberrejectenable  2
systemtraplicense  2

community  1 public
rocommunity public


trapcommunity public
trapsink 10.10.1.172
trapcommunity public
trapsink 10.10.1.208
trapcommunity public
trap2sink 10.10.1.65
trapcommunity public
trapsink 10.100.32.33

trapsource  10.100.3.6
IP440Lab[admin]#

END

$responsesNokiaCheckpoint->{acl_rules} = <<'END';
clish -c "show aclrules"

ACL rule for  Silliness
  
    Position (default rule)   1
    Action:                   accept
    Aggregation class         
    Source IP address:        0.0.0.0
    Source mask length:       0
    Destination IP address:   0.0.0.0
    Destination mask length:  0
    Source port range:        0-65535
    Destination port range:   0-65535
    Protocol:                 any
    TCP established:          no
    TOS:                      any
    DSfield:                  none
    QueueSpec:                none

IP440Lab[admin]#

END

$responsesNokiaCheckpoint->{users} = <<'END';
cat /etc/passwd
root:*:0:0:Root:/var/admin:/bin/csh
admin:*:0:0:Admin:/var/admin:/bin/csh
monitor:*:102:10:Monitor:/var/monitor:/bin/csh
bin:*:3:7:Binaries Commands and Source,,,:/:/nonexistent
nobody:*:65534:65534:Unprivileged user:/nonexistent:/nonexistent
daemon:*:1:31:Owner of many system processes:/nonexistent:/nonexistent
IP440Lab[admin]#

END

$responsesNokiaCheckpoint->{dmesg} = <<'END';
dmesg
Copyright (c) 1982, 1986, 1989, 1991, 1993
        The Regents of the University of California.  All rights reserved.

Resizing packet buffers: mbufs 15360 clusters 14000
releng 1061  01.21.2003-230310
CPU: 333-MHz Celeron (686-class CPU)
real memory  = 201326592 (192M bytes)
avail memory = 187023360 (178M bytes)
chip0 <Intel 82443BX (PAC) PCI/Memory Controller > rev 3 on pci0:0:0
piix0 <Intel 82371AB (PIIX4) PCI to ISA bridge> rev 2 on pci0:7:0
piix1 <Intel 82371AB (PIIX4) PCI to ISA bridge Function> rev 1 on pci0:7:1
Probing for devices on the ISA bus:
scprobe: keyboard RESET failed fe
sc0 at 0x60-0x6f irq 1 on motherboard
sc0: VGA color <16 virtual consoles, flags=0x0>
sio0 at 0x3f8-0x3ff irq 4 on isa
sio0: type 16550A
sio1 at 0x2f8-0x2ff irq 3 on isa
sio1: type 16550A
fdc0 at 0x3f0-0x3f7 irq 6 drq 2 on isa
fdc0: NEC 72065B
fd0: 1.44MB 3.5in
wdc0 at 0x1f0-0x1f7 irq 14 on isa
wdc0: unit 0 (wd0): <WDC WD84AA>, LBA, DMA
wd0: 8455MB (16514064 sectors), LBA geometry: 1027 cyls, 255 heads, 63 S/T
wd0: Physical geometry: 16383 cyls, 16 heads, 63 S/T
wdc1 at 0x170-0x177 irq 15 on isa
wdc1: unit 0 (atapi): <CD-532E-B/1.0A>, removable, accel, ovlap, dma, iordis
wcd0: 5512Kb/sec, 128Kb cache, audio play, 256 volume levels, ejectable tray
wcd0: no disc inside, unlocked
arc(0): unknown rev 0xff
arc(0): Probe failed
arc(1): unknown rev 0xff
arc(1): Probe failed
npx0 on motherboard
npx0: INT 16 interface
piix2 <Intel 82371AB (PIIX4) PCI to ISA bridge Function> rev 1 on pci0:7:2
piix3 <Intel 82371AB (PIIX4) PCI to ISA bridge Function> rev 2 on pci0:7:3
chip1 <Intel 82443BX (PAC) AGP Controller > rev 3 on pci0:1:0
pcidec0 <DEC 21152 PCI-PCI bridge> rev 3 slot 1
tulip0 <Digital DC21143 Fast Ethernet> rev 65 int a irq 9 slot 1 port 1
tulip1 <Digital DC21143 Fast Ethernet> rev 65 int b irq 10 slot 1 port 2
tulip2 <Digital DC21143 Fast Ethernet> rev 65 int c irq 11 slot 1 port 3
tulip3 <Digital DC21143 Fast Ethernet> rev 65 int d irq 12 slot 1 port 4
net_softcall: not inited
net_softcall: not inited
net_softcall: not inited
net_softcall: not inited
changing root device to wd0f
netlog:eth-s1p3 .. enabling 10baseT/UTP port in half duplex mode
netlog:eth-s1p1 .. enabling 10baseT/UTP port in half duplex mode
netlog:eth-s1p4 .. enabling 10baseT/UTP port in half duplex mode
netlog:eth-s1p2 .. enabling 10baseT/UTP port in half duplex mode
IP440Lab[admin]#

END

$responsesNokiaCheckpoint->{hostname} = <<'END';
hostname
IP440Lab
IP440Lab[admin]#

END

$responsesNokiaCheckpoint->{kern_osrelease} = <<'END';
ipsctl kern:osrelease
kern:osrelease = 3.6-FCS6
IP440Lab[admin]#

END

$responsesNokiaCheckpoint->{bios_version} = <<'END';
ipsctl hw:bios:version
hw:bios:version = 4S4EB2X0.86A.00
IP440Lab[admin]#

END

$responsesNokiaCheckpoint->{uptime} = <<'END';
uptime
 5:40PM  up 154 days,  2:03, 5 users, load averages: 0.24, 0.05, 0.02
IP440Lab[admin]#
 
END

$responsesNokiaCheckpoint->{interfaces} = <<'END';
ifconfig -a
eth-s1p1:  flags=4132<UP,BROADCAST,MULTICAST,PRESENT>
        ether 0:c0:95:e2:4f:f0 speed 10M half duplex
eth-s1p2:  flags=4132<UP,BROADCAST,MULTICAST,PRESENT>
        ether 0:c0:95:e2:4f:f1 speed 10M half duplex
eth-s1p3:  flags=4132<UP,BROADCAST,MULTICAST,PRESENT>
        ether 0:c0:95:e2:4f:f2 speed 10M half duplex
eth-s1p4c0:  lname eth-s1p4c0 flags=e7<UP,PHYS_AVAIL,LINK_AVAIL,BROADCAST,MULTICAST,AUTOLINK>
        inet mtu 1500 10.100.3.6/24 broadcast 10.100.3.255
        phys eth-s1p4 flags=4133<UP,LINK,BROADCAST,MULTICAST,PRESENT>
        ether 0:c0:95:e2:4f:f3 speed 10M half duplex
loop0c0:  flags=57<UP,PHYS_AVAIL,LINK_AVAIL,LOOPBACK,MULTICAST>
        inet6 mtu 63000 ::1 --> ::1
        inet mtu 63000 127.0.0.1 --> 127.0.0.1
        phys loop0 flags=10b<UP,LINK,LOOPBACK,PRESENT>
soverf0:  flags=2923<UP,LINK,MULTICAST,PRESENT,IPV6ONLY>
stof0:  flags=2903<UP,LINK,PRESENT,IPV6ONLY>
tun0:  flags=107<UP,LINK,POINTOPOINT,PRESENT>
IP440Lab[admin]#

END

$responsesNokiaCheckpoint->{static_routes} = <<'END';
clish -c "show route"
Codes: C - Connected, S - Static, I - IGRP, R - RIP, B - BGP, O - OSPF
       E - OSPF external, A - Aggregate, K - Kernel Remnant, H - Hidden
       P - Suppressed

S      0.0.0.0/0           via 10.100.3.1 eth-s1p4c0, cost 0, age 13315440  
C      10.100.3/24         is directly connected, eth-s1p4c0  
S      10/8                via 10.100.3.1 eth-s1p4c0, cost 0, age 13315440  
C      127.0.0.1/32        is directly connected, loop0c0  
IP440Lab[admin]#

END

